# Generated by Django 4.2.2 on 2023-06-06 11:05

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('display_name', models.TextField(blank=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('booking_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True)),
                ('start', models.DateTimeField(blank=True, default=None)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('order_number', models.TextField(blank=True)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('suburb', models.TextField(blank=True)),
                ('postcode', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('vehicle_registration', models.TextField(blank=True)),
                ('vehicle_make', models.TextField(blank=True)),
                ('vehicle_model', models.TextField(blank=True)),
                ('vehicle_year', models.TextField(blank=True)),
                ('vehicle_build_description', models.TextField(blank=True)),
                ('fitting_details', models.TextField(blank=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_jobs', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.bookingstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
