# Generated by Django 4.2.2 on 2023-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingevent',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
