# Generated by Django 4.2.2 on 2023-07-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingevent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingevent',
            name='company_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
