# Generated by Django 4.2.2 on 2023-08-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingevent_company_name_bookingevent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='vehicle_build_description',
        ),
    ]
