# Generated by Django 4.2.2 on 2023-08-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_enquiry_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='is_active',
        ),
    ]
